<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Room.Application\Room.Application.csproj" />
    <ProjectReference Include="..\Room.Domain\Room.Domain.csproj" />
  </ItemGroup>

</Project>
